### ISSUE TITLE
cargo build error: "failed to run custom build command for 'alsa-sys v0.1.2'"

### ISSUE THREAD

**Issue by yox-ctrl** [aryakaul/rusty-krab-manager#14]
Hyped to try using the tool, but I ran into the follow error with building the crate.

**output of "cargo run RUST_BACKTRACE=1"**:

```
   Compiling alsa-sys v0.1.2
   Compiling termion v1.5.5
   Compiling smallvec v0.6.13
   Compiling ogg v0.7.0
   Compiling toml v0.5.6
   Compiling serde_json v1.0.45
   Compiling syn v1.0.14
   Compiling lexical-core v0.4.6
error: failed to run custom build command for `alsa-sys v0.1.2`

Caused by:
  process didn't exit successfully: `/home/***/Downloads/rusty-krab-manager/target/debug/build/alsa-sys-ccc713fee0bc9388/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"` did not exit successfully: exit code: 1
--- stderr
Package alsa was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsa.pc\'
to the PKG_CONFIG_PATH environment variable
No package \'alsa\' found"', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**To replicate:** if you feel it helps
my distro: `Pop_OS! v19.10`
my cargo: `cargo 1.40.0 (bc8e4c8be 2019-11-22)`
my rustc: `rustc 1.40.0 (73528e339 2019-12-16)`
I followed the git steps from the *Installation* page

**Comment by aryakaul** [comment]
Hmm try using the `cargo install` method? I also found [this thread](https://github.com/ggez/ggez/issues/278), which might be useful. Try `pkg-config` through `apt get`

**Comment by aryakaul** [comment]
also try [this](https://github.com/Spotifyd/spotifyd/issues/183)!

**Comment by aryakaul** [comment]
Hey bud, any updates on this? Let me know if either thread fixed it. From what I've read installing `libasound2-dev` should fix the issue.

**Comment by yox-ctrl** [comment]
Apologies for the delay. Installing `apt install libasound2-dev` does satisfy the alsa-sys dependency and the crate successfully builds. Thanks!

**Comment by cata0309** [comment]
If someone is receiving the error on Solus try `sudo eopkg it alsa-lib-devel`
