### ISSUE TITLE
on macOS it can't find its own config

### ISSUE THREAD

**Issue by matthiasdebernardini** [aryakaul/rusty-krab-manager#21]
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/32387851/93469832-4ebc6e00-f8f1-11ea-8542-58f404bce444.png">

As you can see in the photo, I have the config file but it wont read it. 

Instead it goes and looks in the application 
Error: configuration file "/Users/matthiasdebernardini/Library/Application Support/rusty-krab-manager/config.toml" not found

I just upgraded to v1 today via cargo.

Any tips?

**Comment by matthiasdebernardini** [comment]
ok so I noticed that dirs crate just assumes that on macOS all the configs live in the application support folder.

Is there a way to support "~/.config" on macOS by default? 

This is a terminal app so most people will be using .config even on macOS, my dotfiles would kindly thank you.

The default location (app support) is better suited for GUI apps.

**Comment by matthiasdebernardini** [comment]
I am gonna give it a shot to use the home dir on macos https://docs.rs/dirs/3.0.1/dirs/fn.home_dir.html

**Comment by aryakaul** [comment]
Yep, looks like the config files for MacOS are in the preferences directory. If you want to force it to use the `.config` directory you can change `main.rs` line 81 to:
```
//let mut default_config = dirs::config_dir().unwrap();
let mut default_config = dirs::home_dir().unwrap();
default_config.push(".config");
```
I'll add a goal for the next release to be a '-c' option where one can manually specify the location of the config file

**Comment by aryakaul** [comment]
Just pinging this, -c option should now work
