### ISSUE TITLE
Unable to start on Mac OS Catalina 10.15.7

### ISSUE THREAD

**Issue by Fouer** [aryakaul/rusty-krab-manager#28]
I can not run the executable after installing, the following error arises:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /Users/*user*/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-krab-manager-1.1.3/src/default_files.rs:55:43

<img width="611" alt="CleanShot 2020-11-03 at 10 39 47@2x" src="https://user-images.githubusercontent.com/1590291/97959689-f0741d80-1dc0-11eb-906f-278c42fe3256.png">

**Comment by aryakaul** [comment]
Hello, sorry I don't have a Mac to replicate this. I think it has something to do with making the default config files. Do you have a config file fully filled out already? MacOS' directory should be something like  `/Users/fouer/Library/Application Support/rusty-krab-manager/config.toml`

**Comment by Fouer** [comment]
Hey, you are probably right, config.toml was absent and when I created it at a given path the error changed to: 
<img width="544" alt="CleanShot 2020-11-04 at 20 59 18@2x" src="https://user-images.githubusercontent.com/1590291/98151034-9ff3e180-1ee0-11eb-9036-e7500229e110.png">
Could you please specify what are the other files required and their default paths?

**Comment by aryakaul** [comment]
Have you filled out the config.toml file with the rest of the information? See the [Config](https://github.com/aryakaul/rusty-krab-manager/wiki/Configuration) and [Usage](https://github.com/aryakaul/rusty-krab-manager/wiki/Usage) pages on the wiki and let me know if anything is unclear. You need to make a task file and point the `task_filepath` config item to its location.

**Comment by Fouer** [comment]
Thx, it works finally :) For some reason $HOME variable didn't work in the config file, it started to work when I changed it to /Users/*user*

**Comment by aryakaul** [comment]
Happy to help! And yes, I'll clarify on the wiki that environment variables like $HOME won't work in the config file
