### ISSUE TITLE
 Add Cargo.lock

### ISSUE THREAD

**Issue by orhun** [aryakaul/rusty-krab-manager#31]
You should consider adding the Cargo.lock file as stated here in the [.gitignore](https://github.com/aryakaul/rusty-krab-manager//blob/master/.gitignore#L5).

See: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by aryakaul** [comment]
added, thanks for the heads up!
